import type { Theme } from '../types/theme';
import { generateId } from '../lib/utils';

const now = Date.now();

export function createSeedThemes(): Theme[] {
  const themes: Theme[] = [
    // === 人文 ===
    {
      id: generateId(),
      title: '手艺人的最后一刻',
      description: '记录即将失传的传统手工艺，聚焦一位老手艺人的日常与坚守，展现人与技艺之间的情感纽带。',
      category: 'humanity',
      difficulty: 'intermediate',
      tags: ['手工艺', '传承', '人文关怀', '非遗'],
      coverImage: '',
      shootingTips: '多用手持镜头增加真实感，特写手部动作，自然光拍摄工坊环境',
      suggestedDuration: '5-8分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '城市守夜人',
      description: '跟随深夜工作的城市守护者——急诊医生、消防员、便利店店员，记录午夜之后不为人知的故事。',
      category: 'humanity',
      difficulty: 'intermediate',
      tags: ['城市', '夜晚', '职业', '纪实'],
      coverImage: '',
      shootingTips: '低光环境拍摄技巧很重要，大光圈镜头必备，注意城市夜景的色彩对比',
      suggestedDuration: '8-12分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '归来仍是少年',
      description: '记录一位老人追寻年轻梦想的故事——学乐器、跑马拉松、写回忆录，诠释"活到老学到老"。',
      category: 'humanity',
      difficulty: 'beginner',
      tags: ['老年', '梦想', '励志', '温情'],
      coverImage: '',
      shootingTips: '大量跟拍镜头，注重表情捕捉，利用慢镜头强调情感时刻',
      suggestedDuration: '5-7分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },

    // === 自然 ===
    {
      id: generateId(),
      title: '微观星球',
      description: '用微距镜头探索城市角落里的微观世界——露珠、昆虫、苔藓，发现身边的自然奇迹。',
      category: 'nature',
      difficulty: 'advanced',
      tags: ['微距', '自然', '生态', '视觉'],
      coverImage: '',
      shootingTips: '微距镜头必备，三脚架稳定，清晨光线最佳，注意景深控制',
      suggestedDuration: '3-5分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '四季物语',
      description: '固定地点拍摄同一场景的四季变化，通过延时摄影展现时间的流转与自然的韵律。',
      category: 'nature',
      difficulty: 'advanced',
      tags: ['四季', '延时', '风景', '时间'],
      coverImage: '',
      shootingTips: '每次拍摄保持完全相同的机位和参数，使用延时摄影，建议跨度一年',
      suggestedDuration: '4-6分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '流浪猫日记',
      description: '跟踪记录城市流浪猫的生存状态，展现人与动物共处的都市生态。',
      category: 'nature',
      difficulty: 'intermediate',
      tags: ['动物', '城市', '生态', '温情'],
      coverImage: '',
      shootingTips: '低角度拍摄猫的视角，长焦镜头保持距离，耐心等待自然行为',
      suggestedDuration: '5-8分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },

    // === 社会 ===
    {
      id: generateId(),
      title: '消失的街区',
      description: '记录城市更新中被拆迁改造的老街区，留住即将消失的城市记忆与市井烟火气。',
      category: 'society',
      difficulty: 'intermediate',
      tags: ['城市变迁', '拆迁', '记忆', '纪实'],
      coverImage: '',
      shootingTips: '多拍固定镜头记录环境，采访原住民，收集老照片做对比',
      suggestedDuration: '6-10分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '菜市场的哲学',
      description: '以菜市场为舞台，展现市井生活中的朴素智慧与人情冷暖。',
      category: 'society',
      difficulty: 'beginner',
      tags: ['市井', '生活', '美食', '人文'],
      coverImage: '',
      shootingTips: '清晨拍摄最热闹，多用中近景捕捉人物表情细节，收环境音',
      suggestedDuration: '4-7分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '数字游民的中国行',
      description: '跟拍一位数字游民在中国各地的旅居生活，探讨新型工作方式与生活理念。',
      category: 'society',
      difficulty: 'intermediate',
      tags: ['数字游民', '旅行', '生活方式', '自由职业'],
      coverImage: '',
      shootingTips: '混合POV和第三人称视角，轻便设备为主，记录工作和生活的切换',
      suggestedDuration: '8-12分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },

    // === 科技 ===
    {
      id: generateId(),
      title: 'AI与我',
      description: '探索AI如何改变普通人的生活与工作，记录一个人与AI工具共处的一周。',
      category: 'technology',
      difficulty: 'intermediate',
      tags: ['AI', '科技', '生活', '未来'],
      coverImage: '',
      shootingTips: '屏幕录制+实拍结合，用画中画展示人机交互，注意版权和隐私',
      suggestedDuration: '6-8分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '旧物新生',
      description: '记录科技达人修复古董电子产品的过程，赋予旧物新的生命力。',
      category: 'technology',
      difficulty: 'intermediate',
      tags: ['修复', '电子', '怀旧', '手工艺'],
      coverImage: '',
      shootingTips: '俯拍桌面操作细节，配合微距展示电子元件，时间快进展示修复过程',
      suggestedDuration: '5-8分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '创业者的24小时',
      description: '贴身记录一位科技创业者的一天，展现创业背后的激情与压力。',
      category: 'technology',
      difficulty: 'beginner',
      tags: ['创业', '科技', '职场', '纪实'],
      coverImage: '',
      shootingTips: '轻便设备跟拍，注意不同场景的快速切换，捕捉真实情绪',
      suggestedDuration: '5-7分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },

    // === 美食 ===
    {
      id: generateId(),
      title: '一碗面的江湖',
      description: '探寻一碗地道地方面的前世今生——从食材溯源到烹饪技艺，讲述面里藏着的江湖故事。',
      category: 'food',
      difficulty: 'intermediate',
      tags: ['美食', '文化', '探店', '传统'],
      coverImage: '',
      shootingTips: '慢镜头拍蒸汽和浇头特写，收同期声（煮面声、交谈声），多用暖色调',
      suggestedDuration: '5-8分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '深夜食堂',
      description: '探访城市深夜还在营业的小店，记录深夜食客的故事与温暖。',
      category: 'food',
      difficulty: 'intermediate',
      tags: ['深夜', '美食', '故事', '城市'],
      coverImage: '',
      shootingTips: '低光环境配合暖色灯光，特写食物和人物表情，营造温馨氛围',
      suggestedDuration: '6-10分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },

    // === 旅行 ===
    {
      id: generateId(),
      title: '一个人的朝圣',
      description: '跟随一位徒步者完成一条经典长线（如川藏线、茶马古道），记录独处中的思考与成长。',
      category: 'travel',
      difficulty: 'advanced',
      tags: ['徒步', '旅行', '自我探索', '风景'],
      coverImage: '',
      shootingTips: '轻量化设备，无人机航拍大景，GoPro记录第一人称视角，注意充电',
      suggestedDuration: '10-15分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '小城故事',
      description: '选择一个不为人知的小城，用慢旅行的方式记录当地人的日常生活与风土人情。',
      category: 'travel',
      difficulty: 'beginner',
      tags: ['小城', '旅行', '人文', '慢生活'],
      coverImage: '',
      shootingTips: '避免游客视角，深入当地人生活，多用固定镜头，注意声音采集',
      suggestedDuration: '6-10分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '秘境探索',
      description: '发现并记录一处鲜为人知的自然或人文秘境，用镜头揭开它的神秘面纱。',
      category: 'travel',
      difficulty: 'advanced',
      tags: ['探险', '秘境', '自然', '发现'],
      coverImage: '',
      shootingTips: '无人机必备，准备多种焦段镜头，做好户外防护，安全第一',
      suggestedDuration: '8-12分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },

    // === 文化 ===
    {
      id: generateId(),
      title: '戏如人生',
      description: '记录一位戏曲演员的台前幕后，展现传统文化在当代的生存状态与传承困境。',
      category: 'culture',
      difficulty: 'intermediate',
      tags: ['戏曲', '传统', '舞台', '传承'],
      coverImage: '',
      shootingTips: '舞台拍摄注意灯光变化，后台跟拍捕捉准备细节，采访要有深度',
      suggestedDuration: '8-12分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '字里行间',
      description: '探访一家独立书店或图书馆，记录书与人的故事，探讨阅读在数字时代的意义。',
      category: 'culture',
      difficulty: 'beginner',
      tags: ['书店', '阅读', '文化', '安静'],
      coverImage: '',
      shootingTips: '安静环境注意快门声，多用稳定器和滑轨拍书架，暖光营造静谧感',
      suggestedDuration: '4-7分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '民族的色彩',
      description: '记录少数民族的传统节庆或仪式，用镜头捕捉独特的民族美学与文化内涵。',
      category: 'culture',
      difficulty: 'advanced',
      tags: ['少数民族', '节庆', '传统', '色彩'],
      coverImage: '',
      shootingTips: '提前了解文化禁忌，多用广角拍大场面和服饰，尊重拍摄对象意愿',
      suggestedDuration: '8-15分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },

    // === 运动 ===
    {
      id: generateId(),
      title: '极限48小时',
      description: '记录一位极限运动爱好者的挑战之旅——攀岩、冲浪、滑板或跑酷，展现突破自我的过程。',
      category: 'sports',
      difficulty: 'advanced',
      tags: ['极限运动', '挑战', '青春', '热血'],
      coverImage: '',
      shootingTips: 'GoPro多角度（头盔、胸前、板头），无人机跟拍，慢镜头抓关键动作',
      suggestedDuration: '5-8分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '晨练中国',
      description: '记录中国各地清晨的独特健身风景——太极、广场舞、毽子、单杠，展现民间运动文化。',
      category: 'sports',
      difficulty: 'beginner',
      tags: ['晨练', '民间', '运动', '文化'],
      coverImage: '',
      shootingTips: '清晨光线柔和，广角拍公园全景，中近景捕捉人物动作细节',
      suggestedDuration: '4-7分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: generateId(),
      title: '胜负之外',
      description: '记录一场业余体育比赛（马拉松、自行车、业余足球），聚焦参与者而非冠军，讲述参赛背后的故事。',
      category: 'sports',
      difficulty: 'intermediate',
      tags: ['比赛', '业余', '坚持', '故事'],
      coverImage: '',
      shootingTips: '多机位拍摄（起点、途中、终点），采访多位参赛者，捕捉真实情绪',
      suggestedDuration: '6-10分钟',
      relatedThemes: [],
      isBuiltIn: true,
      createdAt: now,
      updatedAt: now,
    },
  ];

  return themes;
}

export async function seedThemesIfEmpty(): Promise<void> {
  const { db } = await import('./database');
  const count = await db.themes.count();
  if (count === 0) {
    const themes = createSeedThemes();
    await db.themes.bulkAdd(themes);
    console.log(`✅ ${themes.length} 个主题已植入`);
  }
}
